id: IA497D89F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T21:06:50+00:00'
last_modified: '2022-06-10T05:26:33.360703+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13603
  title: རྫོགས་པ་ཆེན་པོ་ཡེ་ཤེས་བླ་མའི་སྤྱི་དོན་སྙིང་ཐིག་མ་བུའི་ལྡེ་མིག་ཀུན་བཟང་ཐུགས་ཀྱི་ཊི་ཀ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6C60:
      image_group_id: I1KG13627
      title: Volume 1 of rdzogs pa chen po ye shes bla ma'i spyi don snying thig ma
        bu'i lde mig kun bzang thugs kyi Ti ka
      total_pages: 610
      order: 1
      base_file: 6C60.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
